### ISSUE TITLE
Hello, may I ask how can I run Chinese datasets? Do I need to switch to mBART or modify certain settings? Thank you.

### ISSUE THREAD

**Issue by PYMAQ** [SeungoneKim/SICK_Summarization#1]

**Comment by PYMAQ** [comment]
Could you please help me clarify whether the contents in COMET_data will be automatically generated if I switch to a Chinese dataset or I need to find a Chinese domain knowledge dataset by myself?

**Comment by kyle8581** [comment]
Thank you for reaching out to us with your question regarding our project. Please note that simply replacing the COMET model with mBART will not generate a Chinese dataset, as mBART is not specifically trained to generate commonsense knowledge in Chinese. However, if you have access to a model that is capable of generating Chinese commonsense knowledge, you may be able to modify the configuration to obtain a Chinese dataset, as you mentioned.

**Comment by PYMAQ** [comment]
Excuse me, may I ask if the model in this link (https://huggingface.co/fnlp/bart-base-chinese) is a Chinese BART model? I'm curious whether it can generate Chinese commonsense. It seems to generate for the masked position, right?

**Comment by PYMAQ** [comment]
Is it possible to run your model as long as I change the comet model into Chinese, and then generate the corresponding Chinese common sense reasoning sentences for each sentence of my Chinese conversation dataset, plus the Chinese Bart and Chinese conversation dataset?（是不是只要我把comet模型换成中文的，然后对我的中文对话数据集的每一句话生成对应的中文常识推理句子，再加上中文的bart，以及中文的对话数据集，就可以跑你的模型了？）

**Comment by SeungoneKim** [comment]
Hello, thanks for reaching us out & for your interest in our paper!
I'll answer to your questions one-by-one.

Q1) The Chinese BART model you shared to us seems to be a general purpose LM, not a commonsense Model. As you could check from the paper, the commonsense model we used (for English domain) are COMET[1] and PARA-COMET[2]. These models were explicitly trained to generate commonsense knowledge. In my opinion, I think that it will not be enough commonsense knowledge.

Q2) I definitely think our code will work if you manage to gather Chinese commonsense knowledge & use a multilingual BART model instead of the original BART model for training to summarize dialogues. Please let us know if there are any technical issues.


[1] Hwang, J. D., Bhagavatula, C., Le Bras, R., Da, J., Sakaguchi, K., Bosselut, A., & Choi, Y. (2021, May). (comet-) atomic 2020: On symbolic and neural commonsense knowledge graphs. In Proceedings of the AAAI Conference on Artificial Intelligence (Vol. 35, No. 7, pp. 6384-6392).
[2] Gabriel, S., Bhagavatula, C., Shwartz, V., Le Bras, R., Forbes, M., & Choi, Y. (2021, May). Paragraph-level commonsense transformers with recurrent memory. In Proceedings of the AAAI Conference on Artificial Intelligence (Vol. 35, No. 14, pp. 12857-12865).

**Comment by PYMAQ** [comment]
@inproceedings{li2022c3kg,
  title={C3KG: A Chinese Commonsense Conversation Knowledge Graph},
  author={Li, Dawei and Li, Yanran and Zhang, Jiayi and Li, Ke and Wei, Chen and Cui, Jianwei and Wang, Bin},
  booktitle={Findings of the Association for Computational Linguistics: ACL 2022},
  pages={1369--1383},
  year={2022}
}

Hello, I have spent half a day finding this paper. I wonder if it qualifies as a Chinese domain commonsense knowledge model that you mentioned? Can I use it? This is the code repository and it seems to have both the model and data. Could you please take a look and see if it meets your requirements? Thank you.
url：https://github.com/XiaoMi/C3KG

**Comment by SeungoneKim** [comment]
Yes I think the model provided will serve as an excellent chinese commonsense model. Just make sure you set the relations same with the C3KG paper, not with either COMET or PARACOMET.
